[options]
admin_passwd = admin_master_password
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password
addons_path = /mnt/extra-addons,/mnt/extra-addons-custom
log_level = info
